name: C/C++ CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: Ubuntu-20.04

    steps:
#- uses: actions/checkout@v2
    - name: see around
      run: ls; pwd; set
#    - name: compile
#      run: g++ hello.cpp
#    - name: ./a.out
#      run: ./a.out
